"""Increase short description size for project

Revision ID: 0b1cc5c2ba5d
Revises: 6275a7243ac3
Create Date: 2025-09-17 11:44:23.732629

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0b1cc5c2ba5d'
down_revision = '6275a7243ac3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('main_project', schema=None) as batch_op:
        batch_op.alter_column('short_description',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=1000),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('main_project', schema=None) as batch_op:
        batch_op.alter_column('short_description',
               existing_type=sa.String(length=1000),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###
