"""Add date for projects

Revision ID: 490c21337570
Revises: 0b1cc5c2ba5d
Create Date: 2025-09-23 17:08:59.699488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '490c21337570'
down_revision = '0b1cc5c2ba5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('main_project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_future', sa.Boolean(), nullable=False, server_default="FALSE"))
        batch_op.add_column(sa.Column('start_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('end_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('main_project', schema=None) as batch_op:
        batch_op.drop_column('end_date')
        batch_op.drop_column('start_date')
        batch_op.drop_column('is_future')

    # ### end Alembic commands ###
