"""Creation of project table

Revision ID: 544cdf53c9b1
Revises: 
Create Date: 2025-08-27 19:52:04.472749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '544cdf53c9b1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('main_project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('short_title', sa.String(length=64), nullable=False),
    sa.Column('short_description', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('short_title')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('main_project')
    # ### end Alembic commands ###
