"""Add ticket link for representation

Revision ID: 84783327cc12
Revises: 85d2fbe0e15d
Create Date: 2026-03-03 23:42:13.864993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84783327cc12'
down_revision = '85d2fbe0e15d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('main_representation_place', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ticket_link', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('main_representation_place', schema=None) as batch_op:
        batch_op.drop_column('ticket_link')

    # ### end Alembic commands ###
