"""Added attributes for representation places and dates

Revision ID: 85d2fbe0e15d
Revises: 8e1273e7dcdb
Create Date: 2026-03-03 19:27:29.918529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85d2fbe0e15d'
down_revision = '8e1273e7dcdb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('main_representation_date', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.DateTime(), nullable=False))

    with op.batch_alter_table('main_representation_place', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('main_representation_place', schema=None) as batch_op:
        batch_op.drop_column('name')

    with op.batch_alter_table('main_representation_date', schema=None) as batch_op:
        batch_op.drop_column('date')

    # ### end Alembic commands ###
