"""Representation places and dates

Revision ID: 8e1273e7dcdb
Revises: b4fb5267eed4
Create Date: 2026-03-03 19:21:39.664017

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e1273e7dcdb'
down_revision = 'b4fb5267eed4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('main_representation_place',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['main_project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('main_representation_date',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('representation_place_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['representation_place_id'], ['main_representation_place.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('main_representation_date')
    op.drop_table('main_representation_place')
    # ### end Alembic commands ###
