"""Project informations

Revision ID: 90529b58fc67
Revises: 490c21337570
Create Date: 2025-09-26 16:59:48.099204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90529b58fc67'
down_revision = '490c21337570'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('main_project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('full_title', sa.String(length=255), nullable=False, server_default="Unknown"))
        batch_op.add_column(sa.Column('poster_desc', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('video_link', sa.String(length=1024), nullable=True))
        batch_op.add_column(sa.Column('distribution_text', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('main_project', schema=None) as batch_op:
        batch_op.drop_column('distribution_text')
        batch_op.drop_column('video_link')
        batch_op.drop_column('poster_desc')
        batch_op.drop_column('full_title')

    # ### end Alembic commands ###
