"""display order for member

Revision ID: b4fb5267eed4
Revises: 90529b58fc67
Create Date: 2025-10-05 14:36:47.563551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4fb5267eed4'
down_revision = '90529b58fc67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('main_member', schema=None) as batch_op:
        batch_op.add_column(sa.Column('display_order', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('main_member', schema=None) as batch_op:
        batch_op.drop_column('display_order')

    # ### end Alembic commands ###
